version: '3.8'

services:
  myapp:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - APP_MODE=${APP_MODE}
      - REFRESH_MIGRATIONS=${REFRESH_MIGRATIONS}
      - DB_HOST=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./laravel:/app
    depends_on:
      - mariadb
    networks:
      - app

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - ./db:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
    networks:
      - app
networks:
  app: